services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: contable.76
      MYSQL_DATABASE: railway
      MYSQL_USER: postgres
      MYSQL_PASSWORD: contable.76
    volumes:
      - mysqlDataContable:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysqlDataContable:
