export const cuentasCOntables = {
  'cuentas contables': {
    '1000': 'Activo',
    '1100': 'Activo Circulante',
    '1110': 'Efectivo y Equivalentes',
    '1111': 'Caja',
    '1112': 'Bancos',
    '1113': 'Inversiones temporales',
    '1120': 'Cuentas por Cobrar',
    '1121': 'Clientes',
    '1122': 'Documentos por cobrar',
    '1123': 'Deudores diversos',
    '1124': 'Funcionarios y empleados',
    '1125': 'Estimación para cuentas incobrables',
    '1130': 'Inventarios',
    '1131': 'Inventario de mercancías',
    '1132': 'Inventario de materias primas',
    '1133': 'Inventario de productos en proceso',
    '1134': 'Inventario de productos terminados',
    '1135': 'Estimación por obsolescencia de inventarios',
    '1140': 'Inversiones a Corto Plazo',
    '1150': 'Pagos Anticipados',
    '1151': 'Seguros pagados por anticipado',
    '1152': 'Rentas pagadas por anticipado',
    '1153': 'Intereses pagados por anticipado',
    '1200': 'Activo No Circulante',
    '1210': 'Propiedad, Planta y Equipo',
    '1211': 'Terrenos',
    '1212': 'Edificios',
    '1213': 'Maquinaria y equipo',
    '1214': 'Equipo de transporte',
    '1215': 'Mobiliario y equipo de oficina',
    '1216': 'Equipo de cómputo',
    '1217': 'Depreciación acumulada',
    '1220': 'Activos Intangibles',
    '1221': 'Patentes',
    '1222': 'Marcas',
    '1223': 'Derechos de autor',
    '1224': 'Crédito mercantil',
    '1225': 'Amortización acumulada',
    '1230': 'Inversiones a Largo Plazo',
    '1240': 'Otros Activos',

    // Pasivo
    '2000': 'Pasivo',
    '2100': 'Pasivo Circulante',
    '2110': 'Cuentas por Pagar',
    '2111': 'Proveedores',
    '2112': 'Acreedores diversos',
    '2120': 'Préstamos a Corto Plazo',
    '2130': 'Impuestos por Pagar',
    '2131': 'IVA por pagar',
    '2132': 'ISR por pagar',
    '2133': 'IETU por pagar',
    '2140': 'Anticipos de Clientes',
    '2150': 'Dividendos por Pagar',

    // Pasivo No Circulante
    '2200': 'Pasivo No Circulante',
    '2210': 'Préstamos a Largo Plazo',
    '2220': 'Obligaciones por Beneficios a Empleados',
    '2221': 'Pensiones y jubilaciones',
    '2222': 'Prima de antigüedad',
    '2230': 'Impuestos Diferidos',

    // Capital Contable
    '3000': 'Capital Contable',
    '3100': 'Capital Social',
    '3110': 'Capital social fijo',
    '3120': 'Capital social variable',
    '3200': 'Utilidades Retenidas',
    '3210': 'Utilidades de ejercicios anteriores',
    '3220': 'Utilidad del ejercicio',
    '3300': 'Reservas',
    '3310': 'Reserva legal',
    '3320': 'Reserva para recompra de acciones',
    '3400': 'Otras Cuentas de Capital',
    '3410': 'Superávit por revaluación',
    '3420': 'Efecto acumulado por conversión',

    // Ingresos
    '4000': 'Ingresos',
    '4100': 'Ventas',
    '4110': 'Ventas de productos',
    '4120': 'Ventas de servicios',

    // Ingresos Operativos
    '4200': 'Otros Ingresos',
    '4210': 'Ingresos por intereses',
    '4220': 'Ganancia en venta de activos fijos',
    '4230': 'Ganancia en inversiones',
    '4240': 'Ganancia en inversiones a corto plazo',
    '4250': 'Ganancia en operaciones de financiamiento',
    '4260': 'Ganancia en intereses e intereses de reembolso',
    '4270': 'Ganancia en utilidades',
    '4280': 'Ganancia en utilidades de efectivo',
    '4290': 'Ganancia en utilidades de inversiones',
    '4300': 'Ganancia en utilidades de instrumentos de medida y evaluación',
    '4310': 'Ganancia en utilidades de seguros',
    '4320': 'Ganancia en utilidades de seguros de vida',
    '4330': 'Ganancia en utilidades de seguros de trabajo',
    '4340': 'Ganancia en utilidades de seguros de riesgo',
    '4350': 'Ganancia en utilidades de seguros de accidentes personales',

    // Costos  (considerados egresos)
    '5000': 'Costos',
    '5100': 'Costo de Ventas',
    '5110': 'Costo de productos vendidos',
    '5120': 'Costo de servicios prestados',

    // Gastos (considerados egresos)
    '6000': 'Gastos',
    '6100': 'Gastos de Operación',
    '6110': 'Gastos de venta',
    '6120': 'Gastos de administración',
    '6130': 'Gastos de personal',
    '6140': 'Depreciación y amortización',
    '6200': 'Gastos Financieros',
    '6210': 'Intereses pagados',
    '6220': 'Pérdida cambiaria',
    '6300': 'Otros Gastos',
    '6310': 'Pérdida en venta de activos fijos',

    // Egresos (considerados egresos)
    '7000': 'Egresos',
    '7100': 'Egresos Operativos',
    '7110': 'Gastos Generales',
    '7120': 'Gastos Administrativos',
    '7130': 'Gastos Comerciales',
    '7200': 'Egresos Financieros',
    '7210': 'Intereses Pagados',
    '7220': 'Comisiones Bancarias',
    '7300': 'Egresos No Operativos',
    '7310': 'Pérdidas por Venta',
    '7320': 'Donaciones',
  },
};
